[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

# Mustang Color Scheme
#[[plugins]]
#repo = 'croaker/mustang-vim'

# tomorrow Color Scheme
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

# hybrid Color Scheme
#[[plugins]]
#repo = 'w0ng/vim-hybrid'


