[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo    = 'Shougo/neomru.vim'
depends = ['Shougo/unite.vim']

[[plugins]]
repo    = 'ujihisa/unite-colorscheme'
depends = ['Shougo/unite.vim']

# 補完の強化
# インサートモードに入ったら読み込む
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'

# use rsense
[[plugins]]
repo  = 'NigoroJr/rsense'
on_ft = ['ruby']

[[plugins]]
repo    = 'supermomonga/neocomplete-rsense.vim'
depends = ['Shougo/neocomplete','marcus/rsense']

[[plugins]]
repo  = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo  = '5t111111/neat-json.vim'
on_ft = ['json']

[[plugins]]
repo = 'tpope/vim-obsession'
